apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "kevinsena/hello-go"
          startupProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 4
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            failureThreshold: 1

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
